# Generated by Django 4.0.1 on 2022-01-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comenzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oras', models.CharField(max_length=45, null=True)),
                ('Strada', models.CharField(max_length=45, null=True)),
                ('Nume_Client', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firma', models.CharField(max_length=45, null=True)),
                ('Data_expirare', models.DateField(blank=True, default=None, null=True)),
                ('Data_fabricatie', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oras', models.CharField(max_length=45, null=True)),
                ('Strada', models.CharField(max_length=45, null=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShop.comenzi')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShop.produse')),
            ],
        ),
    ]
