# Generated by Django 4.0.1 on 2022-01-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comenzi',
            name='Nume_Client',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='comenzi',
            name='Oras',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='comenzi',
            name='Strada',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='Oras',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='Strada',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='produse',
            name='Firma',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
    ]
